from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ModelCatalogEntry:
    method_id: str
    display_name: str
    formula: str
    inputs: str
    outputs: str
    assumptions: str
    limitations: str
    status: str


MODEL_CATALOG: dict[str, ModelCatalogEntry] = {
    "linear_iq": ModelCatalogEntry(
        "linear_iq",
        "Linear: I(q) vs q",
        "I(q)",
        "Finite q and I(q).",
        "Direct intensity curve.",
        "Best first inspection view; preserves calibrated negative intensities.",
        "Large dynamic range can hide weak features.",
        "production",
    ),
    "semilog_iq": ModelCatalogEntry(
        "semilog_iq",
        "Semi-log: ln I(q) vs q",
        "ln I(q)",
        "Finite q and positive I(q).",
        "Log-intensity curve.",
        "Non-positive I(q) values are excluded before logarithms.",
        "Not valid for zero or negative intensity points.",
        "production",
    ),
    "loglog_power_law_check": ModelCatalogEntry(
        "loglog_power_law_check",
        "Log-log / power-law: ln I(q) vs ln q",
        "ln I(q) = a + b ln q",
        "Positive q and positive I(q).",
        "Power-law slope inspection.",
        "A stable slope can suggest scale-dependent scattering behavior.",
        "The slope alone is not unique structural proof.",
        "visual_check",
    ),
    "guinier_plot": ModelCatalogEntry(
        "guinier_plot",
        "Guinier: ln I(q) vs q\u00b2",
        "ln I(q) = ln I(0) - Rg\u00b2q\u00b2/3",
        "Positive I(q), positive q, selected low-q interval.",
        "Guinier linearity and Rg-sensitive view.",
        "Requires an appropriate low-q range and residual check.",
        "Rg is not automatically a particle radius except under specific morphology assumptions.",
        "model_free",
    ),
    "local_slope_plot": ModelCatalogEntry(
        "local_slope_plot",
        "Local slope: \u03b1(q) vs q",
        "\u03b1(q) = -d ln I / d ln q",
        "Positive q and positive I(q).",
        "Local power-law exponent curve.",
        "Useful for identifying approximate power-law regions.",
        "Derivative estimates are noise-sensitive.",
        "model_free",
    ),
    "kratky_plot": ModelCatalogEntry(
        "kratky_plot",
        "Kratky: q\u00b2I(q) vs q",
        "q\u00b2I(q)",
        "Finite q and I(q).",
        "Kratky representation.",
        "Interpretation depends on material class and scattering contrast.",
        "A peak or plateau is descriptive, not a full model by itself.",
        "descriptive",
    ),
    "porod_plot": ModelCatalogEntry(
        "porod_plot",
        "Porod: q\u2074I(q) vs q",
        "q\u2074I(q)",
        "Finite q and I(q).",
        "Porod representation and plateau inspection.",
        "Requires a suitable high-q range and two-phase assumptions for surface estimates.",
        "Without contrast and stable plateau, it is descriptive only.",
        "descriptive",
    ),
    "invariant_integrand_plot": ModelCatalogEntry(
        "invariant_integrand_plot",
        "Invariant integrand: q\u00b2I(q) vs q",
        "q\u00b2I(q)",
        "Finite q and I(q).",
        "Finite-range invariant contribution density.",
        "Shows measured q-range contribution only.",
        "Does not extrapolate to q = 0 or q = infinity.",
        "model_free",
    ),
    "invariant_logq_contribution_plot": ModelCatalogEntry(
        "invariant_logq_contribution_plot",
        "Log-q contribution: q\u00b3I(q) vs ln q",
        "Q = \u222b q\u00b3I(q) d ln q",
        "Positive q and finite I(q).",
        "Scale-budget contribution spectrum.",
        "Useful for seeing which q ranges dominate the measured invariant.",
        "Not a substitute for extrapolated total invariant analysis.",
        "model_free",
    ),
    "peak_spacing_plot": ModelCatalogEntry(
        "peak_spacing_plot",
        "Peak / d-spacing: I(q) vs q, d = 2\u03c0/q*",
        "d = 2\u03c0/q*",
        "Finite q and I(q), optional detectable peak q*.",
        "Peak position and characteristic spacing annotation.",
        "Peak q* can indicate a periodicity, correlation distance, or characteristic spacing.",
        "d is not an automatic particle diameter.",
        "visual_check",
    ),
    "q_to_d_secondary_axis": ModelCatalogEntry(
        "q_to_d_secondary_axis",
        "q-to-d secondary axis",
        "d = 2\u03c0/q",
        "Plots whose x-axis is raw positive q.",
        "Approximate real-space scale axis.",
        "Helps link q trends to characteristic length scales.",
        "Do not mix this with Guinier Rg or particle diameter without a model.",
        "descriptive",
    ),
    "shoulder_visual_check": ModelCatalogEntry(
        "shoulder_visual_check",
        "Shoulder / low-q visual check",
        "visual inspection on ln I(q) vs ln q or Guinier views",
        "Positive q and positive I(q) for log views.",
        "Visual indication of shoulders or low-q features.",
        "Useful for guiding range selection and follow-up analysis.",
        "The software does not automatically assign a structure model from a shoulder.",
        "visual_check",
    ),
    "sphere_form_factor": ModelCatalogEntry(
        "sphere_form_factor",
        "Sphere form factor",
        "P(q) = [3(sin(qR) - qR cos(qR))/(qR)\u00b3]\u00b2",
        "q, intensity, radius R, scale, background, contrast assumptions.",
        "Model-dependent sphere radius and scale parameters.",
        "Valid only when a monodisperse sphere approximation is physically justified.",
        "A good fit does not uniquely prove spherical morphology; polydispersity, background, and q range can bias R.",
        "model_dependent",
    ),
    "core_shell_sphere_form_factor": ModelCatalogEntry(
        "core_shell_sphere_form_factor",
        "Core-shell sphere form factor",
        "P(q) from core and shell scattering-length-density contrast amplitudes.",
        "q, intensity, core radius, shell thickness, contrasts, scale, background.",
        "Model-dependent core radius, shell thickness, scale, and background.",
        "Requires known or defensible contrast hierarchy and a core-shell morphology.",
        "Parameters can be correlated; background and contrast uncertainty can dominate weak-shell fits.",
        "model_dependent",
    ),
    "ellipsoid_form_factor": ModelCatalogEntry(
        "ellipsoid_form_factor",
        "Ellipsoid form factor",
        "Orientation-averaged ellipsoid P(q; a, b).",
        "q, intensity, semi-axes, scale, background, optional polydispersity.",
        "Model-dependent ellipsoid dimensions and aspect ratio.",
        "Assumes an ellipsoidal morphology and appropriate orientation averaging.",
        "Aspect ratio can be non-unique over a limited q range.",
        "model_dependent",
    ),
    "cylinder_form_factor": ModelCatalogEntry(
        "cylinder_form_factor",
        "Cylinder form factor",
        "Orientation-averaged cylinder P(q; R, L).",
        "q, intensity, radius, length, scale, background.",
        "Model-dependent cylinder radius, length, and scale.",
        "Requires a cylinder-like morphology and enough q range to separate radius and length effects.",
        "Short rods, disks, and ellipsoids can give similar limited-range scattering.",
        "model_dependent",
    ),
    "disk_form_factor": ModelCatalogEntry(
        "disk_form_factor",
        "Disk form factor",
        "Orientation-averaged thin disk P(q; R, T).",
        "q, intensity, disk radius, thickness, scale, background.",
        "Model-dependent disk radius and thickness.",
        "Requires platelet/disk morphology assumptions.",
        "Thickness and background can be difficult to separate at high q.",
        "model_dependent",
    ),
    "gaussian_chain_model": ModelCatalogEntry(
        "gaussian_chain_model",
        "Gaussian chain model",
        "Debye chain function P(q) = 2(exp(-u) + u - 1)/u\u00b2, u = q\u00b2Rg\u00b2",
        "Positive q, positive intensity, Rg, scale, background.",
        "Model-dependent polymer-chain Rg and scale.",
        "Appropriate for flexible polymer-chain assumptions.",
        "Do not apply directly to inorganic particles or aggregates without polymer-chain justification.",
        "model_dependent",
    ),
    "DAB_two_phase_model": ModelCatalogEntry(
        "DAB_two_phase_model",
        "Debye-Anderson-Brumberger two-phase model",
        "I(q) = I(0)/(1 + q\u00b2\u03be\u00b2)\u00b2",
        "q, intensity, correlation length \u03be, scale, background.",
        "Empirical two-phase random-medium correlation length.",
        "Assumes a random two-phase medium with exponential correlation.",
        "It is empirical and does not identify a unique morphology by itself.",
        "model_dependent",
    ),
    "mass_fractal_empirical_model": ModelCatalogEntry(
        "mass_fractal_empirical_model",
        "Mass-fractal empirical model",
        "I(q) \u221d q\u207b\u1d48 in the fractal interval",
        "Positive q and I(q), selected power-law interval.",
        "Descriptive mass-fractal exponent candidate.",
        "Requires a stable power-law interval and plausible dimension range.",
        "A slope alone is not unique structural proof.",
        "descriptive",
    ),
    "surface_fractal_empirical_model": ModelCatalogEntry(
        "surface_fractal_empirical_model",
        "Surface-fractal empirical model",
        "I(q) \u221d q\u207b\u03b1, with 3 < \u03b1 < 4 for surface-fractal interpretation",
        "Positive q and I(q), selected high-q power-law interval.",
        "Descriptive rough-interface exponent candidate.",
        "Requires a stable high-q interval and appropriate interface assumptions.",
        "Noise, background, and Porod crossover can mimic slope changes.",
        "descriptive",
    ),
    "lamellar_peak_stack_model": ModelCatalogEntry(
        "lamellar_peak_stack_model",
        "Lamellar peak-stack model",
        "q_n \u2248 n\u00b72\u03c0/d",
        "Peak q positions, peak widths, and optional intensity ratios.",
        "Lamellar spacing candidate and harmonic peak inspection.",
        "Requires periodic or quasi-periodic lamellar assumptions.",
        "Harmonic-looking peaks do not automatically identify phase or morphology.",
        "descriptive",
    ),
    "pr_inversion_interface": ModelCatalogEntry(
        "pr_inversion_interface",
        "P(r) inversion interface",
        "I(q) = 4\u03c0 \u222b P(r) sin(qr)/(qr) dr",
        "Broad q coverage, positive intensity, Dmax, regularization, background assumptions.",
        "Experimental pair-distance distribution interface.",
        "Requires validated indirect Fourier transform choices and careful Dmax/regularization selection.",
        "Current interface is experimental and should not be used for formal P(r) conclusions.",
        "experimental",
    ),
    "correlation_function_interface": ModelCatalogEntry(
        "correlation_function_interface",
        "Correlation-function interface",
        "\u03b3(r) from a Fourier transform of corrected I(q)",
        "Corrected intensity, q range, extrapolation assumptions, phase model.",
        "Reserved real-space correlation-function output.",
        "Useful only with explicit structural assumptions and extrapolation policy.",
        "Current interface is reserved and not a validated production analysis.",
        "reserved",
    ),
    "low_q_extrapolation_interface": ModelCatalogEntry(
        "low_q_extrapolation_interface",
        "Low-q extrapolation interface",
        "Guinier or constant extrapolation toward q \u2192 0",
        "Selected low-q interval, extrapolation model, uncertainty and residual checks.",
        "Reserved low-q extrapolated contribution for invariant-style calculations.",
        "Requires explicit model choice and q-range justification.",
        "Not enabled by default; extrapolated totals must report assumptions.",
        "reserved",
    ),
    "high_q_extrapolation_interface": ModelCatalogEntry(
        "high_q_extrapolation_interface",
        "High-q extrapolation interface",
        "Porod q\u207b\u2074 or empirical power-law tail toward q \u2192 \u221e",
        "Selected high-q interval, tail model, background and noise checks.",
        "Reserved high-q extrapolated contribution for invariant or surface estimates.",
        "Requires stable high-q behavior and explicit physical assumptions.",
        "Not enabled by default; total invariant, volume fraction, or surface estimates must carry assumptions.",
        "reserved",
    ),
}


def format_model_catalog_summary() -> str:
    sections = ["Model and plotting transparency:"]
    for entry in MODEL_CATALOG.values():
        sections.extend(
            [
                f"- {entry.display_name}",
                f"  formula: {entry.formula}",
                f"  inputs: {entry.inputs}",
                f"  outputs: {entry.outputs}",
                f"  assumptions: {entry.assumptions}",
                f"  limitations: {entry.limitations}",
                f"  status: {entry.status}",
            ]
        )
    return "\n".join(sections)
